# Generated by Django 6.0.4 on 2026-04-16 23:21

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del documento')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('archivo', models.FileField(upload_to='documentos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx'])], verbose_name='Archivo')),
                ('categoria', models.CharField(choices=[('malla', 'Malla Curricular'), ('requisitos', 'Requisitos de Ingreso'), ('cronograma', 'Cronograma Académico'), ('general', 'Información General'), ('otros', 'Otros Documentos')], default='general', max_length=20, verbose_name='Categoría')),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de subida')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
